site_name: ViroProfiler Documentation
repo_url: https://github.com/deng-lab/viroprofiler
repo_name: deng-lab/viroprofiler
# extra_css:
#   - stylesheets/extra.css
nav:
    - Home: index.md
    - Tutorial: tutorial.md
    - Outputs: output.md
    - Config template: config.md
    - Selecting NF profiles: profiles.md
theme:
  name: material
  palette:
    primary: teal
    accent: deep purple
  icon:
    repo: fontawesome/brands/github-alt
plugins:
  - git-revision-date
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde